---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodemetrics.raf.rs
spec:
  group: raf.rs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nodeName:
                  type: string
                metrics:
                  type: array
                  items:
                    type: object
                    properties:
                      targetNode:
                        type: string
                      bandwidth:
                        type: string
                      latency:
                        type: string
            status:
              type: object
              properties:
                lastUpdated:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: nodemetrics
    singular: nodemetric
    kind: NodeMetric
    shortNames:
    - nm
